MaximeD/gem_updater

.travis.yml, Gemfile, README.md, Rakefile, spec/gem_updater/source_page_parser_spec.rb
Specs should be checked by CI.
Details:
* ADD travis configuration
* ADD Gemfile (for travis)
* REMOVE pry leftover
* ADD build status in `README`
* ADD supported versions in `README`
=> ADD travis

LICENSE.md
Code is missing license, redistribute it under MIT License.
=> ADD license

README.md
`README` could be more pleasant to read if it had more labels.
Details:
* ADD gem version
* ADD code climate
* ADD inch ci
=> ADD labels in README

.travis.yml, gem_updater.gemspec, lib/gem_updater/gem_file.rb, spec/gem_updater/gem_file_spec.rb
Bundler was released to a new version incompatible with current code.
Details:
* UPDATE bundler dependency version
* UPDATE `gem_file.rb` to support latest bundler
* UPDATE `.travis.yml` to use latest bundler
* UPDATE specs
=> UPDATE to latest bundler

lib/gem_updater/source_page_parser.rb
Websites may be down and timeout should be handled.
Related #27
=> ADD timeouts handling

gem_updater.gemspec
=> UPDATE bundler dependency

lib/gem_updater/source_page_parser.rb
=> Add "news" to the list of tracked changelog names

CHANGELOG.md, Gemfile.lock, bin/gem_update, gem_updater.gemspec, lib/gem_updater.rb, lib/gem_updater/gem_file.rb, lib/gem_updater/ruby_gems_fetcher.rb, lib/gem_updater/source_page_parser.rb, lib/gem_updater_template.erb, spec/gem_updater/gem_file_spec.rb, spec/gem_updater/ruby_gems_fetcher_spec.rb, spec/gem_updater/source_page_parser_spec.rb, spec/gem_updater_spec.rb, spec/support/helpers.rb
There are a few things that needs to be refactored.
First, since this is opensource, some "common guidelines" could be
followed, that is mainly removing spaces around parenthesis.
Some methods have also starting to grown beyond legibility and could be
extracted to smaller ones. Lastly, we have some specs calling again and
again the same methods that could be refactored.
TL;DR: no changes, just refactor.
Details
* REFACTOR remove extra spaces
* REFACTOR extract constants
* REFACTOR specs (implicit `each` and common code)
* ADD `Gemfile.lock`
=> REFACTOR code

.travis.yml, CHANGELOG.md
We need to be sure this is also running on ruby `2.3`
=> ADD support for ruby 2.3

CHANGELOG.md, README.md
Just some badges for the readme.
Details
* ADD badges in `README`
=> ADD codacy badges

.travis.yml
We need to be sure this is also running on ruby `2.4`
=> ADD support for ruby 2.4

CHANGELOG.md, README.md
README should display status of dependencies.
Details
* ADD gemnasium badge to README
=> ADD Gemnasium badge

README.md
=> FIX logo url

.travis.yml
We need to ensure this works with ruby `2.6`.
=> ADD support for ruby 2.6

.rubocop.yml, .travis.yml, CHANGELOG.md, Gemfile, Gemfile.lock, Rakefile, bin/gem_update, gem_updater.gemspec, lib/gem_updater.rb, lib/gem_updater/gem_file.rb, lib/gem_updater/ruby_gems_fetcher.rb, lib/gem_updater/source_page_parser.rb, spec/gem_updater/gem_file_spec.rb, spec/gem_updater/ruby_gems_fetcher_spec.rb, spec/gem_updater/source_page_parser_spec.rb, spec/gem_updater_spec.rb, spec/spec_helper.rb, spec/support/helpers.rb
This adds some linting to the project.
Details
* ADD `rubocop` on project and travis
* ADD `memoist` to ease thing
=> ADD rubocop

.rubocop.yml, CHANGELOG.md, Gemfile.lock, gem_updater.gemspec, lib/gem_updater/ruby_gems_fetcher.rb, spec/spec_helper.rb
This adds gem `rubocop-performance` and updates rubocop.
=> ADD rubocop-performance

README.md
=> FIX travis url

lib/gem_updater.rb
This fixes:
```
uninitialized constant GemUpdater::Updater::ERB
```
=> FIX requiring ERB

.github/workflows/ruby.yml
This updates actions/checkout to latest version which will use nodejs 16 instead of nodejs 12.
=> Update workflows with latest version of actions

.github/workflows/ruby.yml, CHANGELOG.md, Makefile
Purpose of the `Makefile` is to define shortcuts for common commands, and serves as convenience.
=> ADD Makefile

spec/acceptance/gem_update_spec.rb
=> FIX acceptance specs

.github/dependabot.yml
Daily is too high for this package.
=> CHANGE dependabot frequency
