MaximeD/gem_updater

gem_updater.gemspec

Gemspec is missing the minimal ruby version. This is important since we
are using keywords arguments which is not supported before ruby 2.0
Details:
* ADD required ruby version in gemspec

ADD minimal ruby version

---

lib/gem_updater/source_page_parser.rb

Some gems are reported to be hosted on `http://github.com` rather than
the `https` version of github. This leads to a redirection which is not
handled by `open-uri`.
Since updating `scheme` after uri creation does not seem to work
anymore, check url before converting is to an `URI`.
Details
* FIX url conversion to `https`

FIX https redirections

---

lib/gem_updater.rb
lib/gem_updater/gem_file.rb
lib/gem_updater/ruby_gems_fetcher.rb
spec/gem_updater/gem_file_spec.rb
spec/gem_updater/ruby_gems_fetcher_spec.rb
spec/gem_updater_spec.rb

For now, `gem_updater` only supports gems hosted on `rubygems.org`,
problem is if user want another source (like `rails-assets.org`), gem
will crash.
Moreover, if a dependant gem has been removed from a new version,
another crash will happen since it considers old gems should always be
part of new ones.
Related #12
Related #13
Details
* REFACTOR to use `Bundler.locked_gems.specs`
* ADD support for other sources (only `rails-assets` for now)
* ADD support for `git` source
* UPDATE doc
* UPDATE specs

ADD support for other sources

---

README.md
bin/gem_update
lib/gem_updater.rb
spec/gem_updater_spec.rb

When passed `--commit` option, gem_update will automatically create a
commit message using the generated diff.
User will be given a chance to edit message before committing. Note that
to allow that, git commit's `-t` option has been used. While it's cool
because it allows both to provide a message and to edit it, it has a
limitation: unmodified message will result in cancelled commit.
To fix that, `--allow-empty-message` has been added. It has problems of
its own: user can't cancel commit manually. It's still possible to
reverse commit if really that was not wanted (after all, user
explicitely asked for it).
It won't be any trouble if there was nothing to update, in case you
wonder: git will see there's nothing to commit and won't even open the
editor.

ADD auto-commit option

---

bin/gem_update

When using `gem_update` locally, it falls back to requiring official
rubygems version, which is quite painful for local dev.
The best would be for it to use the version from where it is called,
which is handled by updating load path.
Details
* ADD a clever load path

ADD clever load path

---

lib/gem_updater/source_page_parser.rb
spec/gem_updater/source_page_parser_spec.rb

Some gems report their homepage to be on github subdomains like
`wiki.github.com`. When this is reported to be the non ssl version of
github, secure redirection will not occur.
Related #18
Details
* FIX redirections on github subdomains
* ADD specs

FIX redirections on github subdomains

---

bin/gem_update

When Gemfile is already up-to-date and `gem_updater` is executed, it
prints a message "Here are your changes" with nothing below. This is not
100% clear. So if no update happenned, it should say so.

UPDATE message when no update has been made

---

lib/gem_updater/source_page_parser.rb
spec/gem_updater/source_page_parser_spec.rb

We can have some links pointing to non ssl version of bitbucket, leading
`open-uri` to crash (just like it would with github).
Related #24
Details
* FIX redirections on bitbucket.org
* ADD specs

FIX redirections of bitbucket

---

CHANGELOG.md
bin/gem_update
lib/gem_updater.rb
lib/gem_updater/gem_file.rb
spec/gem_updater/gem_file_spec.rb
spec/gem_updater_spec.rb

Bundle allows to update only given gems instead of the whole `Gemfile`.
This is done by passing gems names as arguments: `bundle update foo
bar`. `gem_updater` should mimic that behaviour.
Related #1
Details
* REFACTOR binary to use `optparse`
* UPDATE allow passing list of gems to update
* UPDATE specs

UPDATE allow to update only specified gems

---

CHANGELOG.md
bin/gem_update
lib/gem_updater.rb
lib/gem_updater/gem_file.rb
lib/gem_updater/ruby_gems_fetcher.rb
lib/gem_updater/source_page_parser.rb
spec/gem_updater_spec.rb

All logs are made with `puts`.
Well it would be better to use a dedicated one, and since `bundler`
vendors one (through `thor`), we can use this one.
Details
* REFACTOR use `Bundler.ui`
* UPDATE specs

REFACTOR logger

---

CHANGELOG.md
lib/gem_updater.rb

For each updated gem, the process is the same:
looking for it's changelog over the internet.
So for each of them we issue http requests, wait for them to complete,
and once one is over, we proceed to next gem.
This should be multithreaded to gain some time.
Details
* ADD multithreading

ADD multithreading

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb

Switching to bundler logger (#32) changed the return value of
memoized function to fetch changelog. As a consequence when it logs an
error it returns the bundler logger instead of returning nil. So
it displays that changelog link is an object whand it should be nil.
Details
* FIX return value when error

FIX return value

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb

A changelog named `changes` was not recognized.
Related #38
Details
* ADD support for file named `changes`

ADD recognition of Changes

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb

Changelog in `textile` format should also be recognized as something
that may contain anchor.
Related #39
Details
* ADD support of `textile` files

ADD support for textile

---

README.md

The link to the gem updater template in the Readme is broken. Also, [GitHub](https://help.github.com/articles/relative-links-in-readmes/) suggests using relative links in Readme's as a best practice.

Fix gem updater template link in the Readme

---

CHANGELOG.md
lib/gem_updater/ruby_gems_fetcher.rb
spec/gem_updater/ruby_gems_fetcher_spec.rb

We look for an url to parse in response from rubygems.
Ideally, if there is no url, response should not even define it,
but for some gems it will return an empty string,
leading to `open-uri` crashing when attempting to open a blank url.
We should not only check if something is returned, but also that it is
not an empty string.
Related #43
Details
* FIX considering `''` as an url
* UPDATE specs

FIX rubygems returning blank values

---

lib/gem_updater/ruby_gems_fetcher.rb
spec/gem_updater/ruby_gems_fetcher_spec.rb

We may be trigerring too many requests to rubygems.
In which case it won't send us the information we need.
If such a thing happens, we should wait a while before making a new
request.
Details
* FIX making too many requests
* ADD specs

FIX making too many requests

---

lib/gem_updater/source_page_parser.rb

When using an other source (a geminabox install in my case) along with
rubygems, gem_updater will crash when trying to find the changelog
```
uri/common.rb:715:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
from gem_updater-0.4.5/lib/gem_updater/source_page_parser.rb:44:in `correct_uri'
from gem_updater-0.4.5/lib/gem_updater/source_page_parser.rb:13:in `initialize'
from gem_updater-0.4.5/lib/gem_updater.rb:51:in `new'
from gem_updater-0.4.5/lib/gem_updater.rb:51:in `block (2 levels) in fill_changelogs'
```
With this patch, it will simply ignore an unusable url. Don't ask me
why, but the url passed to `SourcePageParser#correct_uri` for a
geminabox gem was an `IO` instead of being a `String`.

FIX using other source with rubygems

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb

Some gems consider their source page is `rubygems.org`. Obviously no
changelog will be find there, but the real problem is that it will fail
in case uri is in `http` instead of `https`.
Details
* ADD `https` redirection for `rubygems.org`

FIX redirections for rubygems

---

.gitignore
CHANGELOG.md
Gemfile
Gemfile.lock
spec/spec_helper.rb

We should have some insights on how much code is covered. In order to do
so, `simplecov` can be used and results parsed by `codacy`.
Details
* ADD gem `simplecov`
* ADD gem `codacy-coverage`
* UPDATE `spec_helper` to generate code coverage
* IGNORE coverage results in `.gitignore`

ADD code coverage

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb

When parsing a github repository, we may find an incorrect changelog
link in case the keyword changelog is used in description too. For
instance:
```
<td>Changelog.md</td> <td>changelog for #2278</td>
```
This will point to the commit message instead of the file.
To prevent this, selector should be more specific.
Details
* FIX css selector for parser

FIX github parser

---

.travis.yml
CHANGELOG.md

Travis is not caching bundler gems by default. Well we can tell it to do
so.
Details
* ENABLE `bundler` caching

ADD bundler caching

---

CHANGELOG.md
Gemfile.lock
gem_updater.gemspec

Details:
* codacy-coverage 0.3.1 → 1.0.0
* json 1.8.3 → 2.0.1
[changelog](https://github.com/flori/json/blob/master/CHANGES.md#2016-07-01-201)
* mini_portile2 2.0.0 → 2.1.0
[changelog](https://github.com/flavorjones/mini_portile/blob/master/CHANGELOG.md#210--2016-01-06)
* nokogiri 1.6.7.2 → 1.6.8
[changelog](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#168--2016-06-06)
* rake 11.1.2 → 11.2.2
[changelog](https://github.com/ruby/rake/blob/master/History.rdoc#1122--2016-06-12)
* rspec 3.4.0 → 3.5.0
* rspec-core 3.4.4 → 3.5.1
[changelog](https://github.com/rspec/rspec-core/blob/master/Changelog.md#351--2016-07-06)
* rspec-expectations 3.4.0 → 3.5.0
[changelog](https://github.com/rspec/rspec-expectations/blob/master/Changelog.md#350--2016-07-01)
* rspec-mocks 3.4.1 → …

UPDATE gems and dependencies

---

CHANGELOG.md
Gemfile.lock
gem_updater.gemspec
lib/gem_updater/gem_file.rb

Since bundler `1.13`, `gem_updater` is not aware of any changelog.
This is because it fails getting new specs set from bundler.
Details
* FIX computing changes

FIX bundler locked gems

---

CHANGELOG.md
lib/gem_updater/source_page_parser.rb
spec/gem_updater/source_page_parser_spec.rb

Some private gems can use something like
```
gem 'private_gem',
git: 'https://<token>:x-oauth-basic@github.com/<organisation>/<project>'
```
This will raise a `userinfo not supported.  [RFC3986] (ArgumentError)`
that should be catched.
Details
* FIX urls with oauth token
* ADD specs

FIX url accessible via OAuth

---

README.md

Code climate badges are not accessible through `img.shields.io` anymore.
Details
* FIX image link for codeclimate

FIX codeclimate badge

---

.travis.yml
CHANGELOG.md

Since ruby `2.5.0` is out, CI should ensure build also passes on this
version.
Details
* ADD CI support for ruby `2.5.0`

ADD CI for ruby 2.5.0

---

README.md

Since gemnasium has been closed (because it got acquired by gitlab), its
badge won't work anymore.
Details
* REMOVE gemnasium badge in `README.md`

REMOVE gemnasium badge

---

CHANGELOG.md
spec/gem_updater/ruby_gems_fetcher_spec.rb

The `sleep` is not stubbed in tests, making an unnecessary wait in
tests.

REFACTOR stubbing sleep in tests

---

.travis.yml
Gemfile.lock
gem_updater.gemspec

When migrating to Bundler 2, there is no possibility to install the gem anymore.
We should update the dependency lock to allow Bundler 2.
Details:
- Bump `bundler` dependency to allow version 2

Unlock `bundler` dependency

---

lib/gem_updater/gem_file.rb

Bundler needs to be required along with its cli, otherwise the following
raises:
```
bundler/cli.rb:111:in `<class:CLI>':
undefined method `feature_flag' for Bundler:Module (NoMethodError)
```

FIX ruby 2.7 compatibility

---

bin/gem_update

As rubocop added the `frozen_string_literal` on top of the executable,
the shebang was not read anymore. That was just an issue on local
development, but still an issue.

FIX shebang

---

.github/workflows/codacy-coverage-reporter.yml
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Gem `codacy-coverage` has been deprecated and replaced by a reporter
available through a github action.

FIX codacy coverage

---

.github/workflows/ruby.yml
.rubocop.yml
CHANGELOG.md
gem_updater.gemspec
lib/gem_updater.rb
lib/gem_updater/source_page_parser.rb

Ruby `2.6` will reach End Of Life by the end of the month. So no need to
keep maintaining it. And ruby `2.5` is already not supported anymore.

REMOVE support for old rubies

---

CHANGELOG.md
gem_updater.gemspec
lib/gem_updater/version.rb
spec/gem_updater/version_spec.rb

Version of the gem should be programmatically accessible, hence a
constant to define it rather than only having it in the gemspec.

ADD version file

---

.github/workflows/ruby.yml
CHANGELOG.md

https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

ADD support for ruby 3.2

---

.github/workflows/ruby.yml
CHANGELOG.md

Ruby 2.7 reached end of life and is no longer maintained.

REMOVE support for ruby 2.7

---

README.md

We are not using travis anymore, so status badge should point to github actions.

UPDATE status badge

---

gem_updater.gemspec

Rubygems allows to [set metadata](https://guides.rubygems.org/specification-reference/#metadata), including where the changelog is located at.

Add gemspec metadata

---

.github/workflows/gem-push.yml

The workflow is failing with error
```
Unknown version 3.3.3 for ruby on ubuntu-22.04
```
This patch relaxes the ruby version to omit the patch, so that ubuntu will use the latest available one.

FIX github worklow for gem-push

---

.github/workflows/ruby.yml

This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.

CI: trust ruby/setup-ruby@v1's bundler-cache

---

.github/workflows/ruby.yml
.rubocop.yml
CHANGELOG.md
gem_updater.gemspec

Ruby 3.0 reach End Of Life on 2024-04-23.

DROP ruby 3.0 support

---

.rubocop.yml

The syntax to load plugins changed.
See: https://docs.rubocop.org/rubocop/extensions.html#loading-extensions

UPDATE syntax for rubocop plugins

---

.github/workflows/ruby-gem.yml
.github/workflows/ruby.yml

This patch is refactoring the GitHub actions to:
1. extract `lint` to a dedicated job, since we don’t need to run it for every ruby version
2. add some emojis for visibility

REFACTOR GitHub actions

---

Makefile
release.rb

This patch is adding a new command `make release` to help with the creation of a new release.

ADD release script

---

release.rb

This part of the regular expression may cause exponential backtracking on strings starting with '# master (unreleased)\n' and containing many repetitions of '\n'.

Fix inefficient regular expression

---

.github/workflows/ruby-gem.yml
.github/workflows/ruby.yml

This patch limits the permissions of the `GITHUB_TOKEN` used in the workflows.

FIX workflow permissions
